import type { Metadata } from 'next';
import { db } from '@/db';
import { primers } from '@/db/schema';
import { eq } from 'drizzle-orm';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const primer = await db.query.primers.findFirst({ where: eq(primers.id, id) });
  const title = primer?.title || primer?.topic || 'Primer Lesson';

  return {
    title,
    description: 'Interactive lesson generated by Primer',
    openGraph: {
      title,
      description: 'Learn Anything via Interactive Lessons',
      images: [
        `/api/og?title=${encodeURIComponent(title)}&description=${encodeURIComponent('Interactive lesson by Primer')}&path=primer`,
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description: 'Interactive lesson generated by Primer',
    },
  };
}

export default function PrimerIdLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
